language: android
script: ./gradlew build assembleRelease
android:
  components:
  - build-tools-20.0.0
  - android-19

deploy:
  - provider: releases
    api_key:
      secure: MyApplication
    file: app/build/outputs/apk/app-release.apk
    on:
      repo: PrafullSingh1992/test
      tags: true


notifications:
  email:
    recipients:
    - prafull.singh@sourcefuse.com
    - prafull.singh@sourcefuse.com
    on_success: always
    on_failure: always
